### PR TITLE
fix: generate - handle enum descriptions with spaces

### LINKED ISSUE #30: values with spaces generate invalid code
I'm trying to generate Go code for the following dbc file:

https://github.com/joshwardell/model3dbc/blob/master/Model3CAN.dbc#L4745

This line
```
VAL_ 280 DI_tractionControlMode 6 "Offroad Assist" 5 "Dyno Mode" 4 "Rolls Mode" 3 "Dev2" 2 "Dev1" 1 "Slip Start" 0 "Standard" ;
```

generates Go code like:

```
type ID118DriveSystemStatus_DI_tractionControlMode uint8

// Value descriptions for the DI_tractionControlMode signal of the ID118DriveSystemStatus message.
const (
ID118DriveSystemStatus_DI_tractionControlMode_Standard ID118DriveSystemStatus_DI_tractionControlMode = 0
ID118DriveSystemStatus_DI_tractionControlMode_Slip Start ID118DriveSystemStatus_DI_tractionControlMode = 1
ID118DriveSystemStatus_DI_tractionControlMode_Dev1 ID118DriveSystemStatus_DI_tractionControlMode = 2
ID118DriveSystemStatus_DI_tractionControlMode_Dev2 ID118DriveSystemStatus_DI_tractionControlMode = 3
ID118DriveSystemStatus_DI_tractionControlMode_Rolls Mode ID118DriveSystemStatus_DI_tractionControlMode = 4
ID118DriveSystemStatus_DI_tractionControlMode_Dyno Mode ID118DriveSystemStatus_DI_tractionControlMode = 5
ID118DriveSystemStatus_DI_tractionControlMode_Offroad Assist ID118DriveSystemStatus_DI_tractionControlMode = 6
)
```

which is invalid due to the spaces

### PR DESCRIPTION
**Pull request by d4l3k**
This replaces non-alphanumeric characters in descriptions with _ when generating the Go enums.

Fixes #30

### CODE REVIEW

File: internal/generate/file.go [hunk 1]
```diff
@@ -121,20 +122,27 @@ func Imports(f *File) {
 	f.P("// Generated code. DO NOT EDIT.")
 }
 
+var nonAlphaNumericRegexp = regexp.MustCompile("[^a-zA-Z0-9]+")
+
+func slugifyString(s string) string {
+	return nonAlphaNumericRegexp.ReplaceAllString(s, "_")
```
Comment (alethenorio) [inline internal/generate/file.go:128]: Wondering whether it makes sense to rather than replace with _, to just remove it, so the example here would be `DriverHeartbeat_Command_HeadlightsOn`. What do you think @odsod ?

Comment (odsod) [reply internal/generate/file.go:128]: Good point! Then we keep the convention of `<Message>_<Signal>_<Value>` - I think that makes sense. What do you think @d4l3k

Comment (d4l3k) [reply internal/generate/file.go:128]: Seems pretty reasonable. The one concern I had was if the description was something like "headlights on" which would result in "headlightson" which is less readable than with the underscore. It's fine in my case

Comment (d4l3k) [reply internal/generate/file.go]: @odsod updated to remove instead of replace

**Comment by d4l3k** [comment]
@odsod @alethenorio can you take another look? Thanks!

**Review by odsod — APPROVED** [review]
Great stuff @d4l3k!

**Review by alethenorio — APPROVED** [review]
Apologies for the delay @d4l3k 

Very nice work
